version: '3.4'

services:
    certbot:
        container_name: evatool_certbot
        image: certbot/certbot:latest
        command: sh -c "certbot certonly --keep --webroot --cert-name ${SERVER_ADDR} -w /var/www/certbot -d ${SERVER_ADDR}"
        entrypoint: ""
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        environment:
            - TERM=xterm
