version: '3'

volumes:
    database_volume:

networks:
    backend:
    frontend:

services:
    database:
        container_name: evatool_database
        image: mysql:8.0.24
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: keycloakdb
        ports:
            - ${DATABASE_PORT}:3306
        networks:
            - backend
        volumes:
            - database_volume:/var/lib/mysql

    auth:
        container_name: evatool_auth
        image: quay.io/keycloak/keycloak:13.0.0
#        image: jboss/keycloak:10.0.2
        environment: 
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_ADDR: database
            DB_VENDOR: MYSQL
            DB_USER: root
            DB_PASSWORD: password
            DB_PORT: 3306
            DB_DATABASE: keycloakdb
#            KEYCLOAK_IMPORT: keycloak-auth-realm.json
        ports:
            - 6006:8080
        networks:
            - backend
        depends_on:
            - database
            - backend

    backend:
        container_name: evatool_backend
        image: evatool/evatool-backend:latest
        environment:
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${BACKEND_PORT}:8080
        networks:
            - backend
            - frontend
        depends_on:
            - database

    frontend:
        container_name: evatool_frontend
        image: evatool/evatool-frontend:latest
        environment:
            HOST_URL: ${HOST_URL}
            BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - ${FRONTEND_PORT}:80
        networks:
            - frontend
        depends_on:
            - backend
            - auth


