version: '3'

volumes:
    database_volume:

networks:
    backend:
    frontend:

services:
    database:
        container_name: evatool_database
        image: mysql:8.0.24
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${DATABASE_PORT}:3306
        networks:
            - backend
        volumes:
            - database_volume:/var/lib/mysql

    backend:
        container_name: evatool_backend
        image: evatool/evatool-backend:latest
        environment:
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${BACKEND_PORT}:8080
        networks:
            - backend
            - frontend
        depends_on:
            - database

    frontend:
        container_name: evatool_frontend
        image: evatool/evatool-frontend:latest
        environment:
            HOST_URL: ${HOST_URL}
            BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - ${FRONTEND_PORT}:80
        networks:
            - frontend
        depends_on:
            - backend

#    keycloak:
#        container_name: evatool_keycloak
#        image: ??
#        environment:
#            - ???
#        networks:
#            - backend
#        depends_on:
#            - database
#             - backend
