name: Publish version to DockerHub

on:
  create:
    tags:
      - '*'

jobs:
  versioning:
    runs-on: ubuntu-latest
    name: Create Version from Tag
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
#      - name: Test
#        run: |
#          echo ${{ env.RELEASE_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy backend image and tag with version
        run: |
          docker pull evatool/evatool-backend:latest
          docker tag evatool/evatool-backend:latest evatool/evatool-backend:${{ env.RELEASE_VERSION }}
          docker push evatool/evatool-backend:${{ env.RELEASE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#      - name: Copy frontend image and tag with version

#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
